# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 322a010c4cd70300228fbcc0f74a9fe9944167706425d8d8d1e5f0cf29d1684b70150baeefaa0fbdea8ae7aeecdc9fe83a2c22600d1b639a2470cba82021f020

test:
  secret_key_base: 8a43c5a0cd60dfbd594fcc66ce9a85e610e78d1f9cba131cf4e7c5ca57e66271101380ad62cfed5f814b62a65391325b9fb40e7639598ebd088c995dbf0d90de

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
